const typeDefs = `
    type User {
        _id: ID
        username: String
        email: String
        password: String
    }

    type ReadyCheck {
        _id: ID
        title: String
        description: String
        createdat: String
        attendees: [User]
    }

    type Auth {
        token: ID!
        user: User
    }

    type Query {
        getUser: User
    }

    type Mutation {
        createUser(
            username: String!,
            email: String!,
            password: String!
        ): Auth
        login(
            email: String!,
            password: String!
        ): Auth
        followFriend (
            username: String!
        ): User
        unfollowFriend (
            username: String!
        ): User
        createReadyCheck(
            title: String!
            description: String
            createdat: String
            attendees: [User]
        ): ReadyCheck
    }
`

module.exports = typeDefs;